-- Perfiles con rol (device o dashboard)
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  role text check (role in ('device', 'dashboard')) not null,
  device_name text,
  created_at timestamp with time zone default now()
);

-- Mediciones de consumo energetico
create table if not exists mediciones (
  id bigint generated by default as identity primary key,
  dispositivo text not null,
  corriente_a double precision not null,
  voltaje_v double precision not null,
  potencia_w double precision not null,
  energia_kwh double precision not null,
  estado text not null,
  creado_en timestamptz not null default now()
);

alter table profiles enable row level security;
alter table mediciones enable row level security;

-- Cada usuario ve y edita solo su propio perfil
create policy "Ver mi perfil" on profiles
  for select using (auth.uid() = id);

create policy "Crear mi perfil" on profiles
  for insert with check (auth.uid() = id);

drop policy if exists "Permitir inserciones de telemetria" on mediciones;
create policy "Permitir inserciones de telemetria"
on mediciones
for insert
to public
with check (true);

drop policy if exists "Permitir lectura de telemetria" on mediciones;
create policy "Permitir lectura de telemetria"
on mediciones
for select
to public
using (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'mediciones'
  ) then
    alter publication supabase_realtime add table public.mediciones;
  end if;
end
$$;
