# Generated by Django 6.1 on 2026-08-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('device_name', models.TextField()),
                ('consumption_kwh', models.FloatField()),
                ('voltage', models.FloatField(null=True)),
                ('current_amps', models.FloatField(null=True)),
                ('notes', models.TextField(null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'energy_readings',
                'managed': False,
            },
        ),
    ]
